mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - '*.xiami.com'
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - {"name":"🇳🇱يومي","type":"trojan","server":"trojan-dis-nl01.globalssh.xyz","port":443,"udp":true,"password":"dc5ce847-53cb-46ff-a667-468cadc31d8e","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"يومي🇩🇪","type":"trojan","server":"trojan-adv-de01.globalssh.xyz","port":443,"udp":true,"password":"970aca0d-afb0-4932-ad16-eb81d575964a","sni":"www.telegram.org","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"يومي🇨🇦","type":"trojan","server":"trojan-ovh-ca01.globalssh.xyz","port":443,"udp":true,"password":"eec2d3f2-3923-4392-adde-e910e209380a","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"🇫🇷howdy","type":"trojan","server":"fr1.test3.net","port":443,"udp":true,"password":"bb3f0000-1c92-11ef-becb-1239d0255272","sni":"www.telegram.org","skip-cert-verify":true}
  - {"name":"🇩🇪howdy","type":"trojan","server":"3.71.84.61","port":443,"udp":true,"password":"F30aVAqwjF","sni":"www.telegram.org","skip-cert-verify":true}
proxy-groups:
  - name: CLASH
    type: select
    proxies:
      - 🇳🇱يومي
      - يومي🇩🇪
      - يومي🇨🇦
      - 🇫🇷howdy
      - 🇩🇪howdy
      - DIRECT
rule-providers:
  ads:
    type: http
    behavior: domain
    path: ./rule/ads.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/main/Provide/ads.yaml
  WhatsApp:
    type: http
    behavior: classical
    path: ./rule/WhatsApp.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/muxt0/clash/main/Provide/WhatsApp.yaml
  direct:
    type: http
    behavior: classical
    path: ./rule/direct.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/main/Provide/direct.yaml
  gamesdomain:
    type: http
    behavior: domain
    path: ./rule/gamesdomain.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/main/Provide/gamesdomain.yaml

rules:
  - RULE-SET,ads,REJECT
  - RULE-SET,WhatsApp,CLASH
  - RULE-SET,direct,DIRECT
  - RULE-SET,gamesdomain,CLASH
# > Final
  - MATCH,CLASH