mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - '*.xiami.com'
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - {"name":"🇫🇷إسبوعي","type":"vmess","server":"fr-full.privateip.net","port":443,"cipher":"auto","uuid":"584836fa-2fe8-4452-9252-fd18fcdd8402","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"2🇫🇷إسبوعي","type":"vmess","server":"uk-full.privateip.net","port":443,"cipher":"auto","uuid":"699f6a94-b96e-4bb8-a955-9d16f2146e76","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"www.pubgmobile.com"}}}
  - {"name":"🇩🇪إسبوعي","type":"vmess","server":"de-full.privateip.net","port":443,"cipher":"auto","uuid":"84f02f85-5ec5-498f-8034-55ee0f0a611e","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"2🇩🇪إسبوعي","type":"vmess","server":"de2-full.privateip.net","port":443,"cipher":"auto","uuid":"c97b82e1-8957-45e0-8fff-32ea1b694e12","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇳🇱إسبوعي","type":"vmess","server":"nl-full.privateip.net","port":443,"cipher":"auto","uuid":"2df92630-67b9-4891-a8ff-7b48de2dd72b","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"2🇳🇱إسبوعي","type":"vmess","server":"nl2-full.privateip.net","port":443,"cipher":"auto","uuid":"5481091d-2e58-4e04-9893-a3bc89c85106","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇸🇪إسبوعي","type":"vmess","server":"se-full.privateip.net","port":443,"cipher":"auto","uuid":"8d78e397-55b6-4ca8-8ab0-ffc3c7353944","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇹🇷إسبوعي","type":"vmess","server":"tr-full.privateip.net","port":443,"cipher":"auto","uuid":"773fb40f-b6f2-41d1-90c4-9b6f572c8e42","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇫🇷howdy","type":"trojan","server":"fr1.test3.net","port":443,"udp":true,"password":"52353de0-2e5d-11ef-a1cb-1239d0255272","sni":"www.telegram.org","skip-cert-verify":true}
  - {"name":"🇨🇦يومي","type":"trojan","server":"trojan-ovh-ca01.globalssh.xyz","port":443,"udp":true,"password":"c9acdcd5-57a4-48c4-a774-09fec208a073","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"1🇺🇸يومي","type":"trojan","server":"trojan-rs-us01.globalssh.xyz","port":443,"udp":true,"password":"04a5b0de-5c49-4dd3-b059-6de19ff8549e","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"2🇺🇸يومي","type":"trojan","server":"trojan-rs-us02.globalssh.xyz","port":443,"udp":true,"password":"d7dd8464-02da-41f7-a6a9-2561fb7a2d0b","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"🇺🇦إسبوعي","type":"vmess","server":"ua-full.privateip.net","port":443,"cipher":"auto","uuid":"61a1381a-f464-439e-8f3a-2ae2c8314b74","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"www.pubgmobile.com"}}}
  - {"name":"🇮🇹إسبوعي","type":"vmess","server":"it-full.privateip.net","port":443,"cipher":"auto","uuid":"d36b3f3c-2b18-48bf-9cad-e759f5253acd","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"tencentgames.helpshift.com","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"tencentgames.helpshift.com"}}}
  - {"name":"🇬🇧RaceVPN","type":"vmess","server":"uk-v2ray.ipracevpn.com","port":443,"cipher":"auto","uuid":"3c5ad319-5a74-4dd9-9d8a-7d6920e48efe","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"tcp"}
  - {"name":"🇩🇪RaceVPN","type":"vmess","server":"de-v2ray.ipracevpn.com","port":443,"cipher":"auto","uuid":"ade552c4-7a89-4bdb-b702-725bd58e1256","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"tcp"}
proxy-groups:
  - name: CLASH
    type: select
    proxies:
      - 🇫🇷إسبوعي
      - 2🇫🇷إسبوعي
      - 🇩🇪إسبوعي
      - 2🇩🇪إسبوعي
      - 🇳🇱إسبوعي
      - 2🇳🇱إسبوعي
      - 🇸🇪إسبوعي
      - 🇹🇷إسبوعي
      - 🇫🇷howdy
      - 🇨🇦يومي
      - 1🇺🇸يومي
      - 2🇺🇸يومي
      - 🇺🇦إسبوعي
      - 🇮🇹إسبوعي
      - 🇬🇧RaceVPN
      - 🇩🇪RaceVPN
  - name: SOCIAL
    type: select
    proxies:
      - REJECT
      - DIRECT
      - CLASH
rule-providers:
  WhatsApp:
    type: http
    behavior: classical
    path: ./rule/WhatsApp.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/muxt0/clash/conf/Provide/WhatsApp.yaml
  direct:
    type: http
    behavior: classical
    path: ./rule/direct.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/conf/Provide/direct.yaml
  Tiktok:
    type: http
    behavior: classical
    path: ./rule/Tiktok.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/conf/Provide/Tiktok.yaml
  instagram:
    type: http
    behavior: domain
    path: ./rule/instagram.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/muxt0/clash/conf/Provide/Instagram.yaml

rules:
  - RULE-SET,WhatsApp,CLASH
  - RULE-SET,direct,DIRECT
  - RULE-SET,Tiktok,SOCIAL
  - RULE-SET,instagram,DIRECT
# > Final
  - MATCH,CLASH