mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - '*.xiami.com'
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - {"name":"🇫🇷إسبوعي","type":"vmess","server":"fr-full.privateip.net","port":443,"cipher":"auto","uuid":"59c94ae0-ddf3-4218-8c47-2656f475bbdd","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"2🇫🇷إسبوعي","type":"vmess","server":"fr2-full.privateip.net","port":443,"cipher":"auto","uuid":"01fe291c-13c6-47dd-8ede-bf89d4a63409","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"www.pubgmobile.com"}}}
  - {"name":"🇩🇪إسبوعي","type":"vmess","server":"de-full.privateip.net","port":443,"cipher":"auto","uuid":"a0a4a467-3713-4cff-897b-c91396d3f053","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"2🇩🇪إسبوعي","type":"vmess","server":"de2-full.privateip.net","port":443,"cipher":"auto","uuid":"5481091d-2e58-4e04-9893-a3bc89c85106","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇳🇱إسبوعي","type":"vmess","server":"nl-full.privateip.net","port":443,"cipher":"auto","uuid":"2f733529-f513-42e6-a1bf-c6dbbfa9ed80","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"2🇳🇱إسبوعي","type":"vmess","server":"nl2-full.privateip.net","port":443,"cipher":"auto","uuid":"5481091d-2e58-4e04-9893-a3bc89c85106","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇸🇪إسبوعي","type":"vmess","server":"se-full.privateip.net","port":443,"cipher":"auto","uuid":"8d78e397-55b6-4ca8-8ab0-ffc3c7353944","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇹🇷إسبوعي","type":"vmess","server":"tr-full.privateip.net","port":443,"cipher":"auto","uuid":"7b8400b1-d733-4226-844a-71b35214b9f7","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇫🇷howdy","type":"trojan","server":"fr1.test3.net","port":443,"udp":true,"password":"52353de0-2e5d-11ef-a1cb-1239d0255272","sni":"www.telegram.org","skip-cert-verify":true}
  - {"name":"🇺🇸يومي","type":"trojan","server":"trojan-rs-us03.globalssh.xyz","port":443,"udp":true,"password":"4188e8e4-c17b-48ac-bea1-b4060c62e63d","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"2🇺🇸يومي","type":"trojan","server":"trojan-rs-us01.globalssh.xyz","port":443,"udp":true,"password":"6e296cd0-9bf7-4215-9584-8f9dde7cf40f","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"3🇺🇸يومي","type":"trojan","server":"trojan-rs-us02.globalssh.xyz","port":443,"udp":true,"password":"d7dd8464-02da-41f7-a6a9-2561fb7a2d0b","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"🇬🇧RaceVPN","type":"vmess","server":"uk-v2ray.ipracevpn.com","port":443,"cipher":"auto","uuid":"7c7dbd4a-c794-4e5c-9eaf-477946c258f9","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"tcp"}
  - {"name":"🇩🇪RaceVPN","type":"vmess","server":"de-v2ray.ipracevpn.com","port":443,"cipher":"auto","uuid":"60565b37-f1d8-4f9e-becd-8be4326e7285","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"tcp"}
proxy-groups:
  - name: CLASH
    type: select
    proxies:
      - 🇫🇷إسبوعي
      - 2🇫🇷إسبوعي
      - 🇩🇪إسبوعي
      - 2🇩🇪إسبوعي
      - 🇳🇱إسبوعي
      - 2🇳🇱إسبوعي
      - 🇸🇪إسبوعي
      - 🇹🇷إسبوعي
      - 🇫🇷howdy
      - 🇺🇸يومي
      - 2🇺🇸يومي
      - 3🇺🇸يومي
      - 🇬🇧RaceVPN
      - 🇩🇪RaceVPN
  - name: SOCIAL
    type: select
    proxies:
      - REJECT
      - DIRECT
      - CLASH
rule-providers:
  WhatsApp:
    type: http
    behavior: classical
    path: ./rule/WhatsApp.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/muxt0/clash/conf/Provide/WhatsApp.yaml
  direct:
    type: http
    behavior: classical
    path: ./rule/direct.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/conf/Provide/direct.yaml
  Tiktok:
    type: http
    behavior: classical
    path: ./rule/Tiktok.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/conf/Provide/Tiktok.yaml
  instagram:
    type: http
    behavior: domain
    path: ./rule/instagram.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/muxt0/clash/conf/Provide/Instagram.yaml

rules:
  - RULE-SET,WhatsApp,CLASH
  - RULE-SET,direct,DIRECT
  - RULE-SET,Tiktok,SOCIAL
  - RULE-SET,instagram,DIRECT
# > Final
  - MATCH,CLASH