mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - '*.xiami.com'
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - {"name":"🇳🇱يومي","type":"trojan","server":"trojan-dis-nl01.globalssh.xyz","port":443,"udp":true,"password":"8ffd6924-163e-4b2e-83df-e5a98cadf746","sni":"gtq6.sct.sc-prod.net","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"🇩🇪يومي","type":"trojan","server":"trojan-adv-de01.globalssh.xyz","port":443,"udp":true,"password":"044af87d-2cbe-4e8d-8b73-86a422d7a616","sni":"tencentgames.helpshift.com","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"🇫🇷howdy","type":"trojan","server":"fr1.test3.net","port":443,"udp":true,"password":"52353de0-2e5d-11ef-a1cb-1239d0255272","sni":"www.telegram.org","skip-cert-verify":true}
  - {"name":"🇨🇦يومي","type":"trojan","server":"trojan-rs-us02.globalssh.xyz","port":443,"udp":true,"password":"68e17937-3a14-477f-a456-cfaebfd83d24","sni":"tencentgames.helpshift.com","skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"trojan-grpc"},"alpn":["h2"]}
  - {"name":"🇸🇪 connecton-se1","type":"vmess","server":"se1.connecton.surf","port":443,"cipher":"auto","uuid":"8f3c1afa-52a3-49d2-936c-5ca69b761e7f","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇫🇮 connecton-fi2","type":"vmess","server":"fi2.connecton.surf","port":443,"cipher":"auto","uuid":"9b4d8301-250d-4116-b3dd-c64e924b234b","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇲🇽 connecton-mx1","type":"vmess","server":"mx1.connecton.surf","port":443,"cipher":"auto","uuid":"1cb9251d-6d5a-4fc3-8e79-d8fef314b225","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇵🇹 connecton-pt1","type":"vmess","server":"pt1.connecton.surf","port":443,"cipher":"auto","uuid":"01b35e75-785b-41be-afa8-9723d55519c9","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇪🇸 connecton-sp2","type":"vmess","server":"sp2.connecton.surf","port":443,"cipher":"auto","uuid":"60dcd84c-c358-4d63-be48-1f799fbd9b69","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇬🇧 connecton-uk2","type":"vmess","server":"uk2.connecton.surf","port":443,"cipher":"auto","uuid":"c9f8cc80-3121-45f0-a02e-c13f536629ce","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇫🇷 connecton-fra3","type":"vmess","server":"fra3.connecton.surf","port":443,"cipher":"auto","uuid":"3aae44d4-d640-46c9-b693-e7737d209c94","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇩🇪 connecton-de3","type":"vmess","server":"de3.connecton.surf","port":443,"cipher":"auto","uuid":"24a3e4ee-9822-4c7e-8e84-3835c0dd09c7","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"vmess","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇫🇷إسبوعي","type":"vmess","server":"fr-full.privateip.net","port":443,"cipher":"auto","uuid":"77abdf56-37a2-4773-95ba-748363518857","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇩🇪إسبوعي","type":"vmess","server":"de-full.privateip.net","port":443,"cipher":"auto","uuid":"145194cf-5e9e-41fe-ad10-96a835621795","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇳🇱إسبوعي","type":"vmess","server":"nl-full.privateip.net","port":443,"cipher":"auto","uuid":"f1dc41c8-bf20-4975-9a93-21be699a4ec6","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇺🇦إسبوعي","type":"vmess","server":"ua-full.privateip.net","port":443,"cipher":"auto","uuid":"8ab959ee-4636-4b5f-8f14-c7eaf2d01fa9","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"www.pubgmobile.com"}}}
  - {"name":"🇹🇷إسبوعي","type":"vmess","server":"tr-full.privateip.net","port":443,"cipher":"auto","uuid":"8c38a4be-2133-4066-96ab-201217946bbc","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"gtq6.sct.sc-prod.net","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"gtq6.sct.sc-prod.net"}}}
  - {"name":"🇮🇹إسبوعي","type":"vmess","server":"it-full.privateip.net","port":443,"cipher":"auto","uuid":"325d2667-6c3b-4e8a-a159-9ce7d376d0d9","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"tencentgames.helpshift.com","network":"ws","ws-opts":{"path":"/RACEVPN","headers":{"host":"tencentgames.helpshift.com"}}}
  - {"name":"🇬🇧RaceVPN","type":"vmess","server":"uk-v2ray.ipracevpn.com","port":443,"cipher":"auto","uuid":"65ac69ce-8b0b-4239-b78e-0bc8f8e3b258","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"tcp"}
  - {"name":"🇩🇪RaceVPN","type":"vmess","server":"de-v2ray.ipracevpn.com","port":443,"cipher":"auto","uuid":"0c0fbc9e-b7d4-4c55-835d-f52832a24333","alterId":0,"tls":true,"skip-cert-verify":true,"servername":"www.pubgmobile.com","network":"tcp"}
proxy-groups:
  - name: CLASH
    type: select
    proxies:
      - 🇳🇱يومي
      - 🇩🇪يومي
      - 🇫🇷howdy
      - 🇨🇦يومي
      - 🇸🇪 connecton-se1
      - 🇫🇮 connecton-fi2
      - 🇲🇽 connecton-mx1
      - 🇵🇹 connecton-pt1
      - 🇪🇸 connecton-sp2
      - 🇬🇧 connecton-uk2
      - 🇫🇷 connecton-fra3
      - 🇩🇪 connecton-de3
      - 🇫🇷إسبوعي
      - 🇩🇪إسبوعي
      - 🇳🇱إسبوعي
      - 🇺🇦إسبوعي
      - 🇹🇷إسبوعي
      - 🇮🇹إسبوعي
      - 🇬🇧RaceVPN
      - 🇩🇪RaceVPN
  - name: SOCIAL
    type: select
    proxies:
      - REJECT
      - DIRECT
      - CLASH
rule-providers:
  WhatsApp:
    type: http
    behavior: classical
    path: ./rule/WhatsApp.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/muxt0/clash/conf/Provide/WhatsApp.yaml
  direct:
    type: http
    behavior: classical
    path: ./rule/direct.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/conf/Provide/direct.yaml
  Tiktok:
    type: http
    behavior: classical
    path: ./rule/Tiktok.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/conf/Provide/Tiktok.yaml
  instagram:
    type: http
    behavior: domain
    path: ./rule/instagram.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/muxt0/clash/conf/Provide/Instagram.yaml

rules:
  - RULE-SET,WhatsApp,CLASH
  - RULE-SET,direct,DIRECT
  - RULE-SET,Tiktok,SOCIAL
  - RULE-SET,instagram,DIRECT
# > Final
  - MATCH,CLASH