port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://puredns.org/dns-query
    - tls://puredns.org:853
  fallback:
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - 108.137.44.39
    - 108.137.44.9
tun:
  enable: true
  stack: system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0

proxy-groups:
  - name: auto
    type: select
    proxies:
      - CA🇨🇦يومي
      - NL🇳🇱يومي
      - DE🇩🇪يومي
  - name: PROXY
    type: select
    proxies:
      - CA🇨🇦يومي
      - NL🇳🇱يومي
      - DE🇩🇪يومي
proxies:
  - name: CA🇨🇦يومي
    type: trojan
    server: trojan-ovh-ca01.globalssh.xyz
    port: 443
    password: 136c8d21-edfa-423e-b84a-b203721e1786
    sni: m.facebook.com
    network: ws
    skip-cert-verify: true
    udp: true
    ws-opts:
      path: /trojan-ws
  - name: NL🇳🇱يومي
    type: trojan
    server: trojan-dis-nl01.globalssh.xyz
    port: 443
    password: fb34cc00-2270-4282-9896-eec18dec27a3
    sni: m.facebook.com
    network: ws
    skip-cert-verify: true
    udp: true
    ws-opts:
      path: /trojan-ws
  - name: DE🇩🇪يومي
    type: trojan
    server: trojan-adv-de02.globalssh.xyz
    port: 443
    password: d7952670-91fc-4e96-bd27-e4461dc0b7dc
    sni: m.facebook.com
    network: ws
    skip-cert-verify: true
    udp: true
    ws-opts:
      path: /trojan-ws
rule-providers:
  ads:
    type: http
    behavior: domain
    path: ./rule/ads.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/main/Provide/ads.yaml
  direct:
    type: http
    behavior: classical
    path: ./rule/direct.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/main/Provide/direct.yaml
  gamesdomain:
    type: http
    behavior: domain
    path: ./rule/gamesdomain.yaml
    interval: 86400
    url: https://raw.githubusercontent.com/vipiraq2008/clash/main/Provide/gamesdomain.yaml

rules:
  - IP-CIDR,10.10.0.0/16,auto
  - RULE-SET,ads,REJECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,gamesdomain,DIRECT
# > Final
  - MATCH,Proxy